THALIA_ROOT=`pwd`/..
THALIA_TEMP_CHECKOUTS=${THALIA_ROOT}/temp-checkouts
THALIA_PROJECT_CLJ_DIR=${THALIA_ROOT}/scripts
THALIA_CLOJUREDOCS_FILES_DIR=${THALIA_ROOT}/doc/clojuredocs

mkdir -p ${THALIA_TEMP_CHECKOUTS}
